-- Generated by EQWOWConverter (EQTradeskillFilterLUA).  Do not edit by hand.
-- The ID ranges the trade skill realm filter uses to tell a Norrath recipe from an Azeroth one.
-- This checked-in copy is only a fallback for a client that has not had a converter run deployed to
-- it yet; the converter overwrites it with the values its own Configuration was built with.
EQ_TradeskillFilterData =
{
	ITEM_ID_MIN = 85000,
	ITEM_ID_MAX = 124000,
	SPELL_ID_MIN = 86900,
};
