//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2024 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EQWOWConverter.Common
{
    // Scraped out of wowdev.wiki/M2/AnimationList on 2024/10/20
    internal enum AnimationType : Int16
    {
        None = -1,
        Stand = 0, // Idle
        Death = 1, // Death
        Spell = 2,
        Stop = 3, // Idle (no movement)
        Walk = 4, // Walk
        Run = 5, // Run
        Dead = 6,
        Rise = 7,
        StandWound = 8, // Wound (Idle)
        CombatWound = 9, // Wound (Combat)
        CombatCritical = 10, // Wound (Critical)
        ShuffleLeft = 11, // Turn Left
        ShuffleRight = 12, // Turn Right
        Walkbackwards = 13, // Walk Backwards
        Stun = 14, // Stun
        HandsClosed = 15, // Idle (no movement, hands closed)
        AttackUnarmed = 16, // Attack (unarmed)
        Attack1H = 17, // Attack (1H Right)
        Attack2H = 18, // Attack (2H)
        Attack2HL = 19, // Attack (2H Large)
        ParryUnarmed = 20, // Block (Unarmed)
        Parry1H = 21, // Block (1H)
        Parry2H = 22, // Block (2H)
        Parry2HL = 23, // Block (2H Large)
        ShieldBlock = 24, // Block (Shield)
        ReadyUnarmed = 25, // Ready (Unarmed)
        Ready1H = 26, // Ready (1H)
        Ready2H = 27, // Ready (2H)
        Ready2HL = 28, // Ready (2H Large)
        ReadyBow = 29, // Ready (Bow)
        Dodge = 30, // Dodge
        SpellPrecast = 31,
        SpellCast = 32,
        SpellCastArea = 33,
        NPCWelcome = 34,
        NPCGoodbye = 35,
        Block = 36,
        JumpStart = 37, // Jump
        Jump = 38, // Fall
        JumpEnd = 39, // Land
        Fall = 40, // Fall
        SwimIdle = 41, // Swim (Idle)
        Swim = 42, // Swim (Forward)
        SwimLeft = 43, // Swim (Left)
        SwimRight = 44, // Swim (Right)
        SwimBackwards = 45, // Swim (Backwards)
        AttackBow = 46, // Shoot (Bow)
        FireBow = 47,
        ReadyRifle = 48, // Ready (Gun/Crossbow)
        AttackRifle = 49, // Shoot (Gun/Crossbow)
        Loot = 50, // Loot
        ReadySpellDirected = 51, // Casting 1
        ReadySpellOmni = 52, // Casting 2
        SpellCastDirected = 53, // Cast 1
        SpellCastOmni = 54, // Cast 2
        BattleRoar = 55, // Battle Shout
        ReadyAbility = 56,
        Special1H = 57, // Critical (1H)
        Special2H = 58, // Critical (2H)
        ShieldBash = 59, // Shield Bash
        EmoteTalk = 60, // Talk
        EmoteEat = 61, // Eat/Drink
        EmoteWork = 62, // Smith
        EmoteUseStanding = 63, // Craft
        EmoteTalkExclamation = 64, // Yell
        EmoteTalkQuestion = 65, // Question
        EmoteBow = 66, // Bow
        EmoteWave = 67, // Wave
        EmoteCheer = 68, // Cheer
        EmoteDance = 69, // Dance
        EmoteLaugh = 70, // Laugh
        EmoteSleep = 71,
        EmoteSitGround = 72,
        EmoteRude = 73, // Rude
        EmoteRoar = 74, // Roar
        EmoteKneel = 75, // Kneel
        EmoteKiss = 76, // Kiss
        EmoteCry = 77, // Cry
        EmoteChicken = 78, // Chicken
        EmoteBeg = 79, // Beg
        EmoteApplaud = 80, // Clap
        EmoteShout = 81, // Shout
        EmoteFlex = 82, // Flex
        EmoteShy = 83, // Shy
        EmotePoint = 84, // Point
        Attack1HPierce = 85, // Stab (Right)
        Attack2HLoosePierce = 86,
        AttackOff = 87, // Attack (1H Left)
        AttackOffPierce = 88, // Stab (Left)
        Sheath = 89, // Sheathe (Back)
        HipSheath = 90, // Sheathe (Sides)
        Mount = 91, // Mount
        RunRight = 92,
        RunLeft = 93,
        MountSpecial = 94,
        Kick = 95, // Kick
        SitGroundDown = 96, // Sit Ground (Begin)
        SitGround = 97, // Sit Ground
        SitGroundUp = 98, // Sit Ground (End)
        SleepDown = 99, // Lie Down (Begin)
        Sleep = 100, // Lie Down
        SleepUp = 101, // Lie Down (End)
        SitChairLow = 102, // Sit Chair (Low)
        SitChairMed = 103, // Sit Chair (Medium)
        SitChairHigh = 104, // Sit Chair (High)
        LoadBow = 105, // Load (Bow)
        LoadRifle = 106, // Load (Gun/Crossbow)
        AttackThrown = 107, // Shoot (Wand)
        ReadyThrown = 108, // Ready (Wand)
        HoldBow = 109, // Aim (Bow)
        HoldRifle = 110, // Aim (Gun/Crossbow)
        HoldThrown = 111, // Ready (Thrown)
        LoadThrown = 112, // Ready (Thrown)
        EmoteSalute = 113, // Salute
        KneelStart = 114, // Kneel (Begin)
        KneelLoop = 115, // Kneel
        KneelEnd = 116, // Kneel (End)
        AttackUnarmedOff = 117,
        SpecialUnarmed = 118, // Critical (Unarmed)
        StealthWalk = 119, // Stealth (Walk)
        StealthStand = 120, // Stealth (Idle)
        Knockdown = 121, // Knock Down
        EatingLoop = 122,
        UseStandingLoop = 123, // Craft
        ChannelCastDirected = 124, // Channel 1
        ChannelCastOmni = 125, // Channel 2
        Whirlwind = 126, // Bladestorm
        Birth = 127, // Emerge
        UseStandingStart = 128, // Craft (Begin)
        UseStandingEnd = 129, // Craft (End)
        CreatureSpecial = 130,
        Drown = 131, // Drown
        Drowned = 132, // Drowned
        FishingCast = 133, // Fish
        FishingLoop = 134, // Fishing
        Fly = 135,
        EmoteWorkNoSheathe = 136, // Smith
        EmoteStunNoSheathe = 137, // Stun
        EmoteUseStandingNoSheathe = 138, // Craft
        SpellSleepDown = 139, // Lie Down (Begin)
        SpellKneelStart = 140, // Kneel (Begin)
        SpellKneelLoop = 141, // Kneel
        SpellKneelEnd = 142, // Kneel (End)
        Sprint = 143, // Sprint
        InFlight = 144,
        Spawn = 145,
        Close = 146,
        Closed = 147,
        Open = 148,
        Opened = 149,
        Destroy = 150,
        Destroyed = 151,
        Rebuild = 152,
        Custom0 = 153,
        Custom1 = 154,
        Custom2 = 155,
        Custom3 = 156,
        Despawn = 157,
        Hold = 158,
        Decay = 159,
        BowPull = 160,
        BowRelease = 161,
        ShipStart = 162,
        ShipMoving = 163,
        ShipStop = 164,
        GroupArrow = 165,
        Arrow = 166,
        CorpseArrow = 167,
        GuideArrow = 168,
        Sway = 169,
        DruidCatPounce = 170,
        DruidCatRip = 171,
        DruidCatRake = 172,
        DruidCatRavage = 173,
        DruidCatClaw = 174,
        DruidCatCower = 175,
        DruidBearSwipe = 176,
        DruidBearBite = 177,
        DruidBearMaul = 178,
        DruidBearBash = 179,
        DragonTail = 180, // Tail Swipe (Dragon)
        DragonStomp = 181, // Thunder Clap
        DragonSpit = 182,
        DragonSpitHover = 183,
        DragonSpitFly = 184,
        EmoteYes = 185, // Yes
        EmoteNo = 186, // No
        JumpLandRun = 187, // Land & Run
        LootHold = 188,
        LootUp = 189,
        StandHigh = 190,
        Impact = 191,
        LiftOff = 192,
        Hover = 193, // Levitate
        SuccubusEntice = 194,
        EmoteTrain = 195, // Train
        EmoteDead = 196,
        EmoteDanceOnce = 197,
        Deflect = 198,
        EmoteEatNoSheathe = 199, // Eat/Drink
        Land = 200,
        Submerge = 201, // Submerge
        Submerged = 202, // Submerged
        Cannibalize = 203, // Cannibalize [Undead and Male Troll Only]
        ArrowBirth = 204,
        GroupArrowBirth = 205,
        CorpseArrowBirth = 206,
        GuideArrowBirth = 207,
        EmoteTalkNoSheathe = 208, // Talk
        EmotePointNoSheathe = 209, // Point
        EmoteSaluteNoSheathe = 210, // Salute
        EmoteDanceSpecial = 211, // Dance Special [Human Only]
        Mutilate = 212, // Stab (Both)
        CustomSpell01 = 213, // Boss Cast 1
        CustomSpell02 = 214, // Boss Channel 1
        CustomSpell03 = 215, // Suspended (Bolvar) [Human Only]
        CustomSpell04 = 216, // Knock on Door [Human Only]
        CustomSpell05 = 217, // Boss Precast
        CustomSpell06 = 218, // Boss Channel 2
        CustomSpell07 = 219, // Boss Channel End
        CustomSpell08 = 220, // Boss Cast 2
        CustomSpell09 = 221,
        CustomSpell10 = 222,
        StealthRun = 223, // Stealth (Walk)
        Emerge = 224,
        Cower = 225, // Cower
        Grab = 226,
        GrabClosed = 227,
        GrabThrown = 228,
        FlyStand = 229, // Fly (Idle)
        FlyDeath = 230,
        FlySpell = 231,
        FlyStop = 232,
        FlyWalk = 233, // Fly (Forward)
        FlyRun = 234, // Fly (Forward)
        FlyDead = 235,
        FlyRise = 236,
        FlyStandWound = 237, // Fly (Wound)
        FlyCombatWound = 238,
        FlyCombatCritical = 239,
        FlyShuffleLeft = 240,
        FlyShuffleRight = 241,
        FlyWalkbackwards = 242,
        FlyStun = 243, // Fly (Backwards)
        FlyHandsClosed = 244,
        FlyAttackUnarmed = 245, // Fly (Attack)
        FlyAttack1H = 246,
        FlyAttack2H = 247,
        FlyAttack2HL = 248,
        FlyParryUnarmed = 249,
        FlyParry1H = 250,
        FlyParry2H = 251,
        FlyParry2HL = 252,
        FlyShieldBlock = 253,
        FlyReadyUnarmed = 254, // Fly (Idle)
        FlyReady1H = 255,
        FlyReady2H = 256,
        FlyReady2HL = 257,
        FlyReadyBow = 258,
        FlyDodge = 259,
        FlySpellPrecast = 260,
        FlySpellCast = 261,
        FlySpellCastArea = 262,
        FlyNPCWelcome = 263,
        FlyNPCGoodbye = 264,
        FlyBlock = 265,
        FlyJumpStart = 266,
        FlyJump = 267,
        FlyJumpEnd = 268,
        FlyFall = 269,
        FlySwimIdle = 270,
        FlySwim = 271,
        FlySwimLeft = 272,
        FlySwimRight = 273,
        FlySwimBackwards = 274,
        FlyAttackBow = 275,
        FlyFireBow = 276,
        FlyReadyRifle = 277,
        FlyAttackRifle = 278,
        FlyLoot = 279,
        FlyReadySpellDirected = 280,
        FlyReadySpellOmni = 281,
        FlySpellCastDirected = 282, // Fly (Cast)
        FlySpellCastOmni = 283,
        FlyBattleRoar = 284,
        FlyReadyAbility = 285,
        FlySpecial1H = 286,
        FlySpecial2H = 287,
        FlyShieldBash = 288,
        FlyEmoteTalk = 289,
        FlyEmoteEat = 290,
        FlyEmoteWork = 291,
        FlyEmoteUseStanding = 292,
        FlyEmoteTalkExclamation = 293,
        FlyEmoteTalkQuestion = 294,
        FlyEmoteBow = 295,
        FlyEmoteWave = 296,
        FlyEmoteCheer = 297,
        FlyEmoteDance = 298,
        FlyEmoteLaugh = 299,
        FlyEmoteSleep = 300,
        FlyEmoteSitGround = 301,
        FlyEmoteRude = 302,
        FlyEmoteRoar = 303,
        FlyEmoteKneel = 304,
        FlyEmoteKiss = 305,
        FlyEmoteCry = 306,
        FlyEmoteChicken = 307,
        FlyEmoteBeg = 308,
        FlyEmoteApplaud = 309,
        FlyEmoteShout = 310,
        FlyEmoteFlex = 311,
        FlyEmoteShy = 312,
        FlyEmotePoint = 313,
        FlyAttack1HPierce = 314,
        FlyAttack2HLoosePierce = 315,
        FlyAttackOff = 316,
        FlyAttackOffPierce = 317,
        FlySheath = 318,
        FlyHipSheath = 319,
        FlyMount = 320,
        FlyRunRight = 321,
        FlyRunLeft = 322,
        FlyMountSpecial = 323,
        FlyKick = 324,
        FlySitGroundDown = 325, // Land and Sit
        FlySitGround = 326, // Sit [Dragon Only]
        FlySitGroundUp = 327, // Takeoff
        FlySleepDown = 328,
        FlySleep = 329,
        FlySleepUp = 330,
        FlySitChairLow = 331,
        FlySitChairMed = 332,
        FlySitChairHigh = 333,
        FlyLoadBow = 334,
        FlyLoadRifle = 335,
        FlyAttackThrown = 336,
        FlyReadyThrown = 337,
        FlyHoldBow = 338,
        FlyHoldRifle = 339,
        FlyHoldThrown = 340,
        FlyLoadThrown = 341,
        FlyEmoteSalute = 342,
        FlyKneelStart = 343,
        FlyKneelLoop = 344,
        FlyKneelEnd = 345,
        FlyAttackUnarmedOff = 346,
        FlySpecialUnarmed = 347,
        FlyStealthWalk = 348,
        FlyStealthStand = 349,
        FlyKnockdown = 350,
        FlyEatingLoop = 351,
        FlyUseStandingLoop = 352,
        FlyChannelCastDirected = 353, // Fly (Channel)
        FlyChannelCastOmni = 354,
        FlyWhirlwind = 355,
        FlyBirth = 356,
        FlyUseStandingStart = 357,
        FlyUseStandingEnd = 358,
        FlyCreatureSpecial = 359,
        FlyDrown = 360,
        FlyDrowned = 361,
        FlyFishingCast = 362,
        FlyFishingLoop = 363,
        FlyFly = 364,
        FlyEmoteWorkNoSheathe = 365,
        FlyEmoteStunNoSheathe = 366,
        FlyEmoteUseStandingNoSheathe = 367,
        FlySpellSleepDown = 368,
        FlySpellKneelStart = 369,
        FlySpellKneelLoop = 370,
        FlySpellKneelEnd = 371,
        FlySprint = 372,
        FlyInFlight = 373,
        FlySpawn = 374,
        FlyClose = 375,
        FlyClosed = 376,
        FlyOpen = 377,
        FlyOpened = 378,
        FlyDestroy = 379,
        FlyDestroyed = 380,
        FlyRebuild = 381,
        FlyCustom0 = 382,
        FlyCustom1 = 383,
        FlyCustom2 = 384,
        FlyCustom3 = 385,
        FlyDespawn = 386,
        FlyHold = 387,
        FlyDecay = 388,
        FlyBowPull = 389,
        FlyBowRelease = 390,
        FlyShipStart = 391,
        FlyShipMoving = 392,
        FlyShipStop = 393,
        FlyGroupArrow = 394,
        FlyArrow = 395,
        FlyCorpseArrow = 396,
        FlyGuideArrow = 397,
        FlySway = 398,
        FlyDruidCatPounce = 399,
        FlyDruidCatRip = 400,
        FlyDruidCatRake = 401,
        FlyDruidCatRavage = 402,
        FlyDruidCatClaw = 403,
        FlyDruidCatCower = 404,
        FlyDruidBearSwipe = 405,
        FlyDruidBearBite = 406,
        FlyDruidBearMaul = 407,
        FlyDruidBearBash = 408,
        FlyDragonTail = 409,
        FlyDragonStomp = 410,
        FlyDragonSpit = 411, // Fly (Bolt from Mouth)
        FlyDragonSpitHover = 412,
        FlyDragonSpitFly = 413,
        FlyEmoteYes = 414,
        FlyEmoteNo = 415,
        FlyJumpLandRun = 416,
        FlyLootHold = 417,
        FlyLootUp = 418,
        FlyStandHigh = 419,
        FlyImpact = 420,
        FlyLiftOff = 421,
        FlyHover = 422,
        FlySuccubusEntice = 423,
        FlyEmoteTrain = 424,
        FlyEmoteDead = 425,
        FlyEmoteDanceOnce = 426,
        FlyDeflect = 427,
        FlyEmoteEatNoSheathe = 428,
        FlyLand = 429,
        FlySubmerge = 430,
        FlySubmerged = 431,
        FlyCannibalize = 432,
        FlyArrowBirth = 433,
        FlyGroupArrowBirth = 434,
        FlyCorpseArrowBirth = 435,
        FlyGuideArrowBirth = 436,
        FlyEmoteTalkNoSheathe = 437,
        FlyEmotePointNoSheathe = 438,
        FlyEmoteSaluteNoSheathe = 439,
        FlyEmoteDanceSpecial = 440,
        FlyMutilate = 441,
        FlyCustomSpell01 = 442,
        FlyCustomSpell02 = 443,
        FlyCustomSpell03 = 444,
        FlyCustomSpell04 = 445,
        FlyCustomSpell05 = 446,
        FlyCustomSpell06 = 447,
        FlyCustomSpell07 = 448,
        FlyCustomSpell08 = 449,
        FlyCustomSpell09 = 450,
        FlyCustomSpell10 = 451,
        FlyStealthRun = 452,
        FlyEmerge = 453,
        FlyCower = 454,
        FlyGrab = 455, // Fly (Critical)
        FlyGrabClosed = 456,
        FlyGrabThrown = 457, // Fly (Attack with Hands)
        ToFly = 458,
        ToHover = 459,
        ToGround = 460,
        FlyToFly = 461,
        FlyToHover = 462,
        FlyToGround = 463, // Fly (Landing)
        Settle = 464, // Fly (Land)
        FlySettle = 465, // Fly (Lower to Land)
        DeathStart = 466,
        DeathLoop = 467,
        DeathEnd = 468,
        FlyDeathStart = 469, // Fly (Death)
        FlyDeathLoop = 470, // Fly (Fall)
        FlyDeathEnd = 471, // Fly (Land Dead)
        DeathEndHold = 472,
        FlyDeathEndHold = 473,
        Strangulate = 474, // Strangulate
        FlyStrangulate = 475,
        ReadyJoust = 476, // Joust (Idle)
        LoadJoust = 477, // Joust (Lower Spear)
        HoldJoust = 478, // Joust (Spear Lowered)
        FlyReadyJoust = 479,
        FlyLoadJoust = 480,
        FlyHoldJoust = 481,
        AttackJoust = 482, // Joust (Attack)
        FlyAttackJoust = 483,
        ReclinedMount = 484, // Mount (Car/Mech)
        FlyReclinedMount = 485,
        ToAltered = 486, // Worgen Transformation [Human Only]
        FromAltered = 487,
        FlyToAltered = 488,
        FlyFromAltered = 489,
        InStocks = 490,
        FlyInStocks = 491,
        VehicleGrab = 492,
        VehicleThrow = 493,
        FlyVehicleGrab = 494,
        FlyVehicleThrow = 495,
        ToAlteredPostSwap = 496,
        FromAlteredPostSwap = 497,
        FlyToAlteredPostSwap = 498,
        FlyFromAlteredPostSwap = 499,
        ReclinedMountPassenger = 500, // Sit (Carriage Backseat)
        FlyReclinedMountPassenger = 501,
        Carry2H = 502, // Carrying [Human Only]
        Carried2H = 503, // Carried [Human Only]
        FlyCarry2H = 504,
        FlyCarried2H = 505,
        EmoteSniff = 506,
        EmoteFlySniff = 507,
        AttackFist1H = 508, // Attack (Unarmed Right)
        FlyAttackFist1H = 509,
        AttackFist1HOff = 510, // Attack (Unarmed Left)
        FlyAttackFist1HOff = 511, // Block (Unarmed)
        ParryFist1H = 512,
        FlyParryFist1H = 513,
        ReadyFist1H = 514, // Ready (Unarmed)
        FlyReadyFist1H = 515,
        SpecialFist1H = 516, // Critical (Unarmed)
        FlySpecialFist1H = 517,
        EmoteReadStart = 518, // Map (Open)
        FlyEmoteReadStart = 519,
        EmoteReadLoop = 520, // Map
        FlyEmoteReadLoop = 521,
        EmoteReadEnd = 522, // Map (Close)
        FlyEmoteReadEnd = 523,
        SwimRun = 524, // Run (Underwater)
        FlySwimRun = 525,
        SwimWalk = 526, // Run (Underwater)
        FlySwimWalk = 527,
        SwimWalkBackwards = 528,
        FlySwimWalkBackwards = 529,
        SwimSprint = 530,
        FlySwimSprint = 531,
        MountSwimIdle = 532,
        FlyMountSwimIdle = 533,
        MountSwimBackwards = 534,
        FlyMountSwimBackwards = 535,
        MountSwimLeft = 536,
        FlyMountSwimLeft = 537,
        MountSwimRight = 538,
        FlyMountSwimRight = 539,
        MountSwimRun = 540,
        FlyMountSwimRun = 541,
        MountSwimSprint = 542,
        FlyMountSwimSprint = 543,
        MountSwimWalk = 544,
        FlyMountSwimWalk = 545,
        MountSwimWalkBackwards = 546,
        FlyMountSwimWalkBackwards = 547,
        MountFlightIdle = 548,
        FlyMountFlightIdle = 549,
        MountFlightBackwards = 550,
        FlyMountFlightBackwards = 551,
        MountFlightLeft = 552,
        FlyMountFlightLeft = 553,
        MountFlightRight = 554,
        FlyMountFlightRight = 555,
        MountFlightRun = 556,
        FlyMountFlightRun = 557,
        MountFlightSprint = 558,
        FlyMountFlightSprint = 559,
        MountFlightWalk = 560,
        FlyMountFlightWalk = 561,
        MountFlightWalkBackwards = 562,
        FlyMountFlightWalkBackwards = 563,
        MountFlightStart = 564,
        FlyMountFlightStart = 565,
        MountSwimStart = 566,
        FlyMountSwimStart = 567,
        MountSwimLand = 568,
        FlyMountSwimLand = 569,
        MountSwimLandRun = 570,
        FlyMountSwimLandRun = 571,
        MountFlightLand = 572,
        FlyMountFlightLand = 573,
        MountFlightLandRun = 574,
        FlyMountFlightLandRun = 575,
        ReadyBlowDart = 576,
        FlyReadyBlowDart = 577,
        LoadBlowDart = 578,
        FlyLoadBlowDart = 579,
        HoldBlowDart = 580,
        FlyHoldBlowDart = 581,
        AttackBlowDart = 582,
        FlyAttackBlowDart = 583,
        CarriageMount = 584, // Carriage (Sit)
        FlyCarriageMount = 585,
        CarriagePassengerMount = 586,
        FlyCarriagePassengerMount = 587,
        CarriageMountAttack = 588, // Carriage (Reins)
        FlyCarriageMountAttack = 589,
        BarTendStand = 590, // Bartender (Idle)
        FlyBarTendStand = 591,
        BarServerWalk = 592, // Waiter (Walk)
        FlyBarServerWalk = 593,
        BarServerRun = 594,
        FlyBarServerRun = 595,
        BarServerShuffleLeft = 596,
        FlyBarServerShuffleLeft = 597,
        BarServerShuffleRight = 598,
        FlyBarServerShuffleRight = 599,
        BarTendEmoteTalk = 600, // Bartender (Talk)
        FlyBarTendEmoteTalk = 601,
        BarTendEmotePoint = 602, // Bartender (Point)
        FlyBarTendEmotePoint = 603,
        BarServerStand = 604, // Waiter (Idle)
        FlyBarServerStand = 605,
        BarSweepWalk = 606,
        FlyBarSweepWalk = 607,
        BarSweepRun = 608,
        FlyBarSweepRun = 609,
        BarSweepShuffleLeft = 610,
        FlyBarSweepShuffleLeft = 611,
        BarSweepShuffleRight = 612,
        FlyBarSweepShuffleRight = 613,
        BarSweepEmoteTalk = 614,
        FlyBarSweepEmoteTalk = 615,
        BarPatronSitEmotePoint = 616,
        FlyBarPatronSitEmotePoint = 617,
        MountSelfIdle = 618, // Running Wild (Idle) [Human & Worgen Only]
        FlyMountSelfIdle = 619,
        MountSelfWalk = 620,
        FlyMountSelfWalk = 621,
        MountSelfRun = 622,
        FlyMountSelfRun = 623,
        MountSelfSprint = 624,
        FlyMountSelfSprint = 625,
        MountSelfRunLeft = 626,
        FlyMountSelfRunLeft = 627,
        MountSelfRunRight = 628,
        FlyMountSelfRunRight = 629,
        MountSelfShuffleLeft = 630,
        FlyMountSelfShuffleLeft = 631,
        MountSelfShuffleRight = 632,
        FlyMountSelfShuffleRight = 633,
        MountSelfWalkBackwards = 634,
        FlyMountSelfWalkBackwards = 635,
        MountSelfSpecial = 636,
        FlyMountSelfSpecial = 637,
        MountSelfJump = 638,
        FlyMountSelfJump = 639,
        MountSelfJumpStart = 640,
        FlyMountSelfJumpStart = 641,
        MountSelfJumpEnd = 642,
        FlyMountSelfJumpEnd = 643,
        MountSelfJumpLandRun = 644,
        FlyMountSelfJumpLandRun = 645,
        MountSelfStart = 646, // Running Wild (Start) [Human & Worgen Only]
        FlyMountSelfStart = 647,
        MountSelfFall = 648,
        FlyMountSelfFall = 649
    }
}
