//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQBlindSpellsLUA
    {
        private static readonly object BlindSpellLock = new object();
        private static SortedSet<int> BlindWOWSpellIDs = new SortedSet<int>();

        // Spell.dbc rows are written block by block (base, creature cast, clicky and worn copies), so each blind block is collected as it is written
        public static void RegisterBlindSpell(int wowSpellID)
        {
            lock (BlindSpellLock)
                BlindWOWSpellIDs.Add(wowSpellID);
        }

        // Writes the set of WOW spell IDs that blind, which EQBlindness.lua looks for in the player's debuffs to black out the game world
        public static void Generate()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQBlindSpellsLUA).  Do not edit by hand.");
            sb.AppendLine("-- The WOW spell IDs of the EQ blind effects.  EQBlindness.lua blacks out the game world while the player has one of these.");
            sb.AppendLine("EQ_BLIND_SPELL_IDS = {");
            lock (BlindSpellLock)
            {
                foreach (int blindWOWSpellID in BlindWOWSpellIDs)
                {
                    sb.Append("[");
                    sb.Append(blindWOWSpellID.ToString());
                    sb.AppendLine("] = true,");
                }
            }
            sb.AppendLine("}");

            // Write it
            string outputFolder = Path.Combine(Configuration.PATH_EXPORT_FOLDER, "MPQReady", "Interface", "FrameXML");
            if (Directory.Exists(outputFolder) == false)
                Directory.CreateDirectory(outputFolder);
            string outputFileFullPath = Path.Combine(outputFolder, "EQBlindSpells.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }
    }
}
