//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using EQWOWConverter.Common;
using EQWOWConverter.Player;
using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQClassCreateLUA
    {
        public static void Generate()
        {
            Dictionary<ClassWOWType, PlayerClassMapping> classMappingsByWOWClass = PlayerClassMapping.GetClassMappingsByWOWClass();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQClassCreateLUA).  Do not edit by hand.");
            sb.AppendLine("EQ_CREATE_CLASSMAP = {");

            // Sorted so repeat runs produce a byte-identical file (avoids phantom patch MPQ diffs)
            List<ClassWOWType> sortedWOWClasses = new List<ClassWOWType>(classMappingsByWOWClass.Keys);
            sortedWOWClasses.Sort();
            foreach (ClassWOWType wowClass in sortedWOWClasses)
            {
                PlayerClassMapping classMapping = classMappingsByWOWClass[wowClass];
                sb.Append("[\"");
                sb.Append(wowClass.ToString().ToUpper());
                sb.Append("\"] = { base = \"");
                sb.Append(GetDisplayNameForEQClass(classMapping.BaseEQClass));
                sb.Append("\", default = \"");
                sb.Append(GetDisplayNameForEQClass(classMapping.DefaultSecondEQClass));
                sb.Append("\", seconds = {");
                for (int i = 0; i < classMapping.AllowedSecondEQClasses.Count; i++)
                {
                    if (i > 0)
                        sb.Append(",");
                    sb.Append(" \"");
                    sb.Append(GetDisplayNameForEQClass(classMapping.AllowedSecondEQClasses[i]));
                    sb.Append("\"");
                }
                sb.AppendLine(" } },");
            }

            sb.AppendLine("}");

            // Write it
            string outputFolder = Path.Combine(Configuration.PATH_EXPORT_FOLDER, "MPQReady", "Interface", "GlueXML");
            if (Directory.Exists(outputFolder) == false)
                Directory.CreateDirectory(outputFolder);
            string outputFileFullPath = Path.Combine(outputFolder, "EQClassCreateData.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }

        private static string GetDisplayNameForEQClass(ClassEQType eqClass)
        {
            switch (eqClass)
            {
                case ClassEQType.None: return "None";
                case ClassEQType.Bard: return "Bard";
                case ClassEQType.Cleric: return "Cleric";
                case ClassEQType.Druid: return "Druid";
                case ClassEQType.Enchanter: return "Enchanter";
                case ClassEQType.Magician: return "Magician";
                case ClassEQType.Monk: return "Monk";
                case ClassEQType.Necromancer: return "Necromancer";
                case ClassEQType.Paladin: return "Paladin";
                case ClassEQType.Ranger: return "Ranger";
                case ClassEQType.Rogue: return "Rogue";
                case ClassEQType.ShadowKnight: return "Shadow Knight";
                case ClassEQType.Shaman: return "Shaman";
                case ClassEQType.Warrior: return "Warrior";
                case ClassEQType.Wizard: return "Wizard";
                default:
                    {
                        Logger.WriteError("Unable to get a display name for EQ Class '", eqClass.ToString(), "'");
                        return "Unknown";
                    }
            }
        }
    }
}
