//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using EQWOWConverter.Common;
using EQWOWConverter.Creatures;
using EQWOWConverter.Creatures.Teleporters;
using EQWOWConverter.Player;
using EQWOWConverter.Zones;
using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQClassCreateLUA
    {
        public static void Generate()
        {
            Dictionary<ClassWOWType, PlayerClassMapping> classMappingsByWOWClass = PlayerClassMapping.GetClassMappingsByWOWClass();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQClassCreateLUA).  Do not edit by hand.");
            sb.AppendLine("EQ_CREATE_CLASSMAP = {");
            List<ClassWOWType> sortedWOWClasses = new List<ClassWOWType>(classMappingsByWOWClass.Keys);
            sortedWOWClasses.Sort();
            foreach (ClassWOWType wowClass in sortedWOWClasses)
            {
                PlayerClassMapping classMapping = classMappingsByWOWClass[wowClass];
                sb.Append("[\"");
                sb.Append(wowClass.ToString().ToUpper());
                sb.Append("\"] = { base = \"");
                sb.Append(GetDisplayNameForEQClass(classMapping.BaseEQClass));
                sb.Append("\", default = \"");
                sb.Append(GetDisplayNameForEQClass(classMapping.DefaultSecondEQClass));
                sb.Append("\", seconds = {");
                for (int i = 0; i < classMapping.AllowedSecondEQClasses.Count; i++)
                {
                    if (i > 0)
                        sb.Append(",");
                    sb.Append(" \"");
                    sb.Append(GetDisplayNameForEQClass(classMapping.AllowedSecondEQClasses[i]));
                    sb.Append("\"");
                }
                sb.AppendLine(" } },");
            }

            sb.AppendLine("}");
            sb.AppendLine("");

            // Start zone and alignment per race+class, for the EverQuest Origins box
            HashSet<ClassWOWType> goodClasses = new HashSet<ClassWOWType>(CreatureTeleportLocationNorrath.GetGoodClasses());
            HashSet<ClassWOWType> evilClasses = new HashSet<ClassWOWType>(CreatureTeleportLocationNorrath.GetEvilClasses());
            Dictionary<RaceType, PlayerWOWRaceProperties> racePropertiesByRaceType = PlayerWOWRaceProperties.GetAllWOWRacePropertiesByRaceType();
            Dictionary<string, ZoneProperties> zonePropertiesByShortName = ZoneProperties.GetZonePropertyListByShortName();

            sb.AppendLine("EQ_CREATE_STARTINFO = {");
            List<(int, int)> sortedRaceClassKeys = new List<(int, int)>(PlayerClassRaceProperties.GetClassRacePropertiesByRaceAndClassID().Keys);
            sortedRaceClassKeys.Sort();
            foreach ((int, int) raceClassKey in sortedRaceClassKeys)
            {
                PlayerClassRaceProperties raceClassProperties = PlayerClassRaceProperties.GetClassRacePropertiesByRaceAndClassID()[raceClassKey];
                RaceType raceType = (RaceType)raceClassProperties.RaceID;
                ClassWOWType classType = (ClassWOWType)raceClassProperties.ClassID;

                string zoneName = raceClassProperties.StartZoneShortName;
                if (zonePropertiesByShortName.ContainsKey(zoneName) == true)
                    zoneName = zonePropertiesByShortName[zoneName].DescriptiveName;
                else
                    Logger.WriteError("EQClassCreateLUA could not find zone properties for start zone short name '", zoneName, "'");

                string alignment = "NEUTRAL";
                if (goodClasses.Contains(classType) == true)
                    alignment = "GOOD";
                else if (evilClasses.Contains(classType) == true)
                    alignment = "EVIL";
                else if (racePropertiesByRaceType.ContainsKey(raceType) == true)
                {
                    switch (racePropertiesByRaceType[raceType].Alignment)
                    {
                        case CreatureFactionAlignmentType.Good: alignment = "GOOD"; break;
                        case CreatureFactionAlignmentType.Evil: alignment = "EVIL"; break;
                        default: break; // Stays neutral
                    }
                }

                sb.Append("[\"");
                sb.Append(GetRaceFileNameForWOWRace(raceType));
                sb.Append("_");
                sb.Append(classType.ToString().ToUpper());
                sb.Append("\"] = { zone = \"");
                sb.Append(zoneName.Replace("\"", ""));
                sb.Append("\", align = \"");
                sb.Append(alignment);
                sb.AppendLine("\" },");
            }
            sb.AppendLine("}");

            // Write it
            string outputFolder = Path.Combine(Configuration.PATH_EXPORT_FOLDER, "MPQReady", "Interface", "GlueXML");
            if (Directory.Exists(outputFolder) == false)
                Directory.CreateDirectory(outputFolder);
            string outputFileFullPath = Path.Combine(outputFolder, "EQClassCreateData.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }

        private static string GetRaceFileNameForWOWRace(RaceType raceType)
        {
            switch (raceType)
            {
                case RaceType.Human: return "HUMAN";
                case RaceType.Orc: return "ORC";
                case RaceType.Dwarf: return "DWARF";
                case RaceType.NightElf: return "NIGHTELF";
                case RaceType.Undead: return "SCOURGE";
                case RaceType.Tauren: return "TAUREN";
                case RaceType.Gnome: return "GNOME";
                case RaceType.Troll: return "TROLL";
                case RaceType.BloodElf: return "BLOODELF";
                case RaceType.Draenei: return "DRAENEI";
                default:
                    {
                        Logger.WriteError("Unable to get a race file name for WOW race '", raceType.ToString(), "'");
                        return "UNKNOWN";
                    }
            }
        }

        private static string GetDisplayNameForEQClass(ClassEQType eqClass)
        {
            switch (eqClass)
            {
                case ClassEQType.None: return "None";
                case ClassEQType.Bard: return "Bard";
                case ClassEQType.Cleric: return "Cleric";
                case ClassEQType.Druid: return "Druid";
                case ClassEQType.Enchanter: return "Enchanter";
                case ClassEQType.Magician: return "Magician";
                case ClassEQType.Monk: return "Monk";
                case ClassEQType.Necromancer: return "Necromancer";
                case ClassEQType.Paladin: return "Paladin";
                case ClassEQType.Ranger: return "Ranger";
                case ClassEQType.Rogue: return "Rogue";
                case ClassEQType.ShadowKnight: return "Shadow Knight";
                case ClassEQType.Shaman: return "Shaman";
                case ClassEQType.Warrior: return "Warrior";
                case ClassEQType.Wizard: return "Wizard";
                default:
                    {
                        Logger.WriteError("Unable to get a display name for EQ Class '", eqClass.ToString(), "'");
                        return "Unknown";
                    }
            }
        }
    }
}
