//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQSpellGenericIconsLUA
    {
        private static readonly object GenericIconLock = new object();
        private static SortedDictionary<int, int> GenericSpellIconEQIDsByWOWSpellID = new SortedDictionary<int, int>();

        // Spell.dbc rows carry the spell gem icon, so the generic icon is collected as the rows are written
        public static void RegisterGenericIcon(int wowSpellID, int spellIconEQID)
        {
            lock (GenericIconLock)
                GenericSpellIconEQIDsByWOWSpellID[wowSpellID] = spellIconEQID;
        }

        // Writes the WOW spell ID to generic spell icon (Spell_EQ_<id>) map, which EQSpellIcons.lua swaps in for the spell gem icon
        // wherever the player's icon type settings (EQ_Options) ask for the generic look
        public static void Generate()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQSpellGenericIconsLUA).  Do not edit by hand.");
            sb.AppendLine("-- EQ spells carry their spell gem icon in Spell.dbc, and EQSpellIcons.lua swaps in the generic spell icon");
            sb.AppendLine("-- where the icon type settings ask for it.  Maps the WOW spell ID to the X in Interface\\Icons\\Spell_EQ_X.");
            sb.AppendLine("EQ_SPELL_GENERIC_ICONS = {");
            lock (GenericIconLock)
            {
                foreach (KeyValuePair<int, int> genericSpellIconEQIDByWOWSpellID in GenericSpellIconEQIDsByWOWSpellID)
                {
                    sb.Append("[");
                    sb.Append(genericSpellIconEQIDByWOWSpellID.Key.ToString());
                    sb.Append("] = ");
                    sb.Append(genericSpellIconEQIDByWOWSpellID.Value.ToString());
                    sb.AppendLine(",");
                }
            }
            sb.AppendLine("}");

            // Write it
            string outputFolder = Path.Combine(Configuration.PATH_EXPORT_FOLDER, "MPQReady", "Interface", "FrameXML");
            if (Directory.Exists(outputFolder) == false)
                Directory.CreateDirectory(outputFolder);
            string outputFileFullPath = Path.Combine(outputFolder, "EQSpellGenericIcons.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }
    }
}
