//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQTradeskillFilterLUA
    {
        // Writes the ID ranges that the EQ_TradeskillFilter addon uses to tell a Norrath recipe from an
        // Azeroth one, so the addon never has to carry a copy of these values itself
        public static void Generate(string addOnFolderPath)
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQTradeskillFilterLUA).  Do not edit by hand.");
            sb.AppendLine("-- The ID ranges the trade skill realm filter uses to tell a Norrath recipe from an Azeroth one.");
            sb.AppendLine("EQ_TradeskillFilterData =");
            sb.AppendLine("{");
            sb.AppendLine(string.Concat("\tITEM_ID_MIN = ", Configuration.SQL_ITEM_TEMPLATE_ENTRY_START.ToString(), ","));
            sb.AppendLine(string.Concat("\tITEM_ID_MAX = ", Configuration.SQL_ITEM_TEMPLATE_ENTRY_END.ToString(), ","));
            sb.AppendLine(string.Concat("\tSPELL_ID_MIN = ", Configuration.DBCID_SPELL_ID_START.ToString(), ","));
            sb.AppendLine("};");

            if (Directory.Exists(addOnFolderPath) == false)
                Directory.CreateDirectory(addOnFolderPath);
            string outputFileFullPath = Path.Combine(addOnFolderPath, "EQ_TradeskillFilterData.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }
    }
}
