//  Author: Nathan Handley (nathanhandley@protonmail.com)
//  Copyright (c) 2026 Nathan Handley
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Text;

namespace EQWOWConverter.WOWFiles
{
    internal class EQVersionLUA
    {
        public static void Generate()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("-- Generated by EQWOWConverter (EQVersionLUA).  Do not edit by hand.");
            sb.Append("EQ_CLIENT_DATA_VERSION = ");
            sb.AppendLine(Configuration.DEPLOY_CLIENT_DATA_VERSION.ToString());
            sb.AppendLine("");
            sb.AppendLine("-- Report the client data version shortly after entering the world, which the server");
            sb.AppendLine("-- compares against the version it was deployed with (kicking the player on a mismatch)");
            sb.AppendLine("local EQVersionReportFrame = CreateFrame(\"Frame\");");
            sb.AppendLine("local EQVersionReportDelayRemaining = nil;");
            sb.AppendLine("EQVersionReportFrame:RegisterEvent(\"PLAYER_ENTERING_WORLD\");");
            sb.AppendLine("EQVersionReportFrame:SetScript(\"OnEvent\", function(self, event)");
            sb.AppendLine("\tEQVersionReportDelayRemaining = 5;");
            sb.AppendLine("end);");
            sb.AppendLine("EQVersionReportFrame:SetScript(\"OnUpdate\", function(self, elapsed)");
            sb.AppendLine("\tif (EQVersionReportDelayRemaining == nil) then");
            sb.AppendLine("\t\treturn;");
            sb.AppendLine("\tend");
            sb.AppendLine("\tEQVersionReportDelayRemaining = EQVersionReportDelayRemaining - elapsed;");
            sb.AppendLine("\tif (EQVersionReportDelayRemaining <= 0) then");
            sb.AppendLine("\t\tEQVersionReportDelayRemaining = nil;");
            sb.AppendLine("\t\tSendChatMessage(\".eqver \" .. EQ_CLIENT_DATA_VERSION, \"SAY\");");
            sb.AppendLine("\tend");
            sb.AppendLine("end);");

            // Write it
            string outputFolder = Path.Combine(Configuration.PATH_EXPORT_FOLDER, "MPQReady", "Interface", "FrameXML");
            if (Directory.Exists(outputFolder) == false)
                Directory.CreateDirectory(outputFolder);
            string outputFileFullPath = Path.Combine(outputFolder, "EQVersionData.lua");
            if (File.Exists(outputFileFullPath) == true)
                File.Delete(outputFileFullPath);
            File.WriteAllText(outputFileFullPath, sb.ToString());
        }
    }
}
